# Generated by Django 6.0.2 on 2026-03-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ConsumedQrToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=255, unique=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=10)),
                ('consumed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
