# Generated by Django 6.0.2 on 2026-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_worksession'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
